/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package antoniogestionvuelos;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anton
 */
public class VentanaVuelos extends javax.swing.JFrame {

    VuelosLogica metodos = new VuelosLogica();
    
    public VentanaVuelos() {
        initComponents();
        metodos.getConnection();
        
        
        DefaultTableModel modelo = new DefaultTableModel();
        try{
            //crea un ResulSet para almacenar los datos que necesites de la tabla vuelos
            Statement stmt = (Statement) metodos.conexion.createStatement();
            ResultSet resultado = (ResultSet) stmt.executeQuery("SELECT cod_vuelo, procedencia, destino FROM vuelos");
            
            //Añadimos al modelo de tabla las columnas necesarias. Debe coincidir con las establecidas en
            //la select asociada al ResultSet
            modelo.addColumn("COD_VUELO");
            modelo.addColumn("PROCEDENCIA");
            modelo.addColumn("DESTINO");
            
            tblRegistroVuelos.setModel(modelo);
            if (stmt != null) {
                stmt.close();
            }
        } catch (SQLException ex) {
            Logger.getLogger(VentanaVuelos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistroVuelos = new javax.swing.JTable();
        btnListado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblRegistroVuelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRegistroVuelos);

        btnListado.setText("LISTADO DE VUELOS");
        btnListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(btnListado, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btnListado, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListadoActionPerformed
        
        //Crea una instancia de la clase DefaultTableModel para construir la tabla que vamos a
        //asociar con el objeto JTable creado en el JFrame
        DefaultTableModel modelo = new DefaultTableModel();
        try{
            //crea un ResulSet para almacenar los datos que necesites de la tabla vuelos
            Statement stmt = (Statement) metodos.conexion.createStatement();
            ResultSet resultado = (ResultSet) stmt.executeQuery("SELECT cod_vuelo, procedencia, destino FROM vuelos");
            
            //Añadimos al modelo de tabla las columnas necesarias. Debe coincidir con las establecidas en
            //la select asociada al ResultSet
            modelo.addColumn("COD_VUELO");
            modelo.addColumn("PROCEDENCIA");
            modelo.addColumn("DESTINO");
            
            //Define un array de objetos para almacenar cada fila de datos
            Object datos[]=new Object[3]; //Numero de columnas de la tabla
            
            // Recorremos la vista resultante de la consulta, la almacenamos en el array de objetos.
            while (resultado.next()){
                for (int i = 0; i < 3; i++) {
                    datos[i]=resultado.getObject(i+1);
                }
                //Añade la fila al modelo de tabla
                modelo.addRow(datos);
            }
            
            //Añade el modelo de tabla creado a el objeto JTable creado en el JFrame
            tblRegistroVuelos.setModel(modelo);
            if (stmt != null) {
                stmt.close(); 
            }
        } catch (SQLException ex) {
            System.out.println("Error al acceder a Usuarios");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnListadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaVuelos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRegistroVuelos;
    // End of variables declaration//GEN-END:variables
}
