/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package antoniogestionvuelos;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anton
 */
public class VentanaPasajeros extends javax.swing.JFrame {

    VuelosLogica metodos = new VuelosLogica();
    
    public VentanaPasajeros() {
        initComponents();
        metodos.getConnection();
        metodos.cargaLista(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etqMensaje = new javax.swing.JLabel();
        etqCodVuelos = new javax.swing.JLabel();
        cbCod = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPasajeros = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etqMensaje.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        etqMensaje.setText("LISTADO DE PASAJEROS PARA CADA VUELO");

        etqCodVuelos.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        etqCodVuelos.setText("Codigo de vuelos");

        cbCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCodActionPerformed(evt);
            }
        });

        tblPasajeros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPasajeros);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(etqCodVuelos)
                        .addGap(75, 75, 75)
                        .addComponent(cbCod, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(etqMensaje))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etqMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etqCodVuelos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCodActionPerformed
        
        //Crea una instancia de la clase DefaultTableModel para construir la tabla que vamos a
        //asociar con el objeto JTable creado en el JFrame
        DefaultTableModel modelo = new DefaultTableModel();
        try{
            //leemos el dato contenido en el com box
            String cad= (String)cbCod.getSelectedItem();
            
            //crea un ResulSet para almacenar los datos que necesites de la tabla vuelos
            Statement stmt = (Statement) metodos.conexion.createStatement();
            ResultSet resultado = (ResultSet) stmt.executeQuery("SELECT num, tipo_plaza, fumador FROM pasajeros where cod_vuelo = " + "'" + cad + "'");
            
            //Añadimos al modelo de tabla las columnas necesarias. Debe coincidir con las establecidas en
            //la select asociada al ResultSet
            modelo.addColumn("NUM");
            modelo.addColumn("TIPO_PLAZA");
            modelo.addColumn("FUMADOR");
            
            //Define un array de objetos para almacenar cada fila de datos
            Object datos[]=new Object[3]; //Numero de columnas de la tabla
            
            // Recorremos la vista resultante de la consulta, la almacenamos en el array de objetos.
            while (resultado.next()){
                for (int i = 0; i < 3; i++) {
                    datos[i]=resultado.getObject(i+1);
                }
                //Añade la fila al modelo de tabla
                modelo.addRow(datos);
            }
            
            //Añade el modelo de tabla creado a el objeto JTable creado en el JFrame
            tblPasajeros.setModel(modelo);
            if (stmt != null) {
                stmt.close(); 
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(VentanaPasajeros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbCodActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPasajeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPasajeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPasajeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPasajeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPasajeros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> cbCod;
    private javax.swing.JLabel etqCodVuelos;
    private javax.swing.JLabel etqMensaje;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPasajeros;
    // End of variables declaration//GEN-END:variables
}
